In [1]:
# importing important libraris
import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import pandas as pd
import warnings
import time
warnings.filterwarnings("ignore")
import numpy as np
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
from selenium.webdriver.chrome.options import Options
options = webdriver.ChromeOptions()
options. add_experimental_option("detach", True)

1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos

You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [15]:
driver1 = webdriver.Chrome("chromedriver.exe")
time.sleep(2)
driver1.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
driver1.maximize_window()
time.sleep(2)

delay = 10
WebDriverWait(driver1, delay).until(EC.presence_of_element_located((By.CLASS_NAME, 'reference')))

ranks = []
views = []
dates = []
video_name = []
singer = []

table = driver1.find_elements_by_xpath('//table[@class = "wikitable sortable jquery-tablesorter"]/tbody/tr/td') 
rank = driver1.find_elements_by_xpath('//td[@align = "center"][1]')  #extracting ranks
view = driver1.find_elements_by_xpath('//td[@align = "center"][2]')  #extracting views
date = driver1.find_elements_by_xpath('//td[@align = "right"]')     #extracting dates

for i in table[1:180:6]:
    video_name.append(i.text)

for j in table[2:180:6]:
    singer.append(j.text)
    
for k in rank:
    ranks.append(k.text)

for l in view:
    views.append(l.text)
    
for m in date:
    dates.append(m.text)

In [16]:
print(len(ranks[:30]))
print(len(views[:30]))
print(len(dates[:30]))
print(len(video_name))
print(len(singer))

30
30
30
30
30

In [18]:
#Making DataFrame
df = pd.DataFrame({"Ranks": ranks[:30], "Video_Name": video_name, "Singer": singer, "Views_in_Millions": views[:30], "Released_Dates": dates[:30]})
df

,Ranks,Video_Name,Singer,Views_in_Millions,Released_Dates
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,10.72,"June 17, 2016"
1,2.,"""Despacito""[6]",Luis Fonsi,7.85,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,6.36,"October 8, 2016"
3,4.,"""Shape of You""[13]",Ed Sheeran,5.72,"January 30, 2017"
4,5.,"""See You Again""[15]",Wiz Khalifa,5.52,"April 6, 2015"
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,5.40,"May 2, 2018"
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,4.64,"March 6, 2014"
7,8.,"""Uptown Funk""[22]",Mark Ronson,4.58,"November 19, 2014"
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,4.57,"February 27, 2018"
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,4.49,"January 31, 2012"
10,11.,"""Gangnam Style""[25]",Psy,4.43,"July 15, 2012"
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,4.08,"May 24, 2018"
12,13.,"""Dame Tu Cosita""[31]",El Chombo,3.94,"April 5, 2018"
13,14.,"""Sugar""[32]",Maroon 5,3.69,"January 14, 2015"
14,15.,"""Roar""[33]",Katy Perry,3.58,"September 5, 2013"
15,16.,"""Counting Stars""[34]",OneRepublic,3.58,"May 31, 2013"
16,17.,"""Sorry""[35]",Justin Bieber,3.54,"October 22, 2015"
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,3.45,"October 7, 2014"
18,19.,"""Axel F""[37]",Crazy Frog,3.36,"June 16, 2009"
19,20.,"""Girls Like You""[38]",Maroon 5,3.29,"May 31, 2018"
20,21.,"""Faded""[39]",Alan Walker,3.28,"December 3, 2015"
21,22.,"""Dark Horse""[40]",Katy Perry,3.27,"February 20, 2014"
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,3.24,"June 25, 2018"
23,24.,"""Let Her Go""[42]",Passenger,3.23,"July 25, 2012"
24,25.,"""Bailando""[43]",Enrique Iglesias,3.21,"April 11, 2014"
25,26.,"""Lean On""[44]",Major Lazer,3.21,"March 22, 2015"
26,27.,"""Shake It Off""[45]",Taylor Swift,3.17,"August 18, 2014"
27,28.,"""Perfect""[46]",Ed Sheeran,3.17,"November 9, 2017"
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,3.14,"June 4, 2010"
29,30.,"""Mi Gente""[48]",J Balvin,3.08,"June 29, 2017"

In [19]:
driver1.close()

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:

A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [40]:
driver2 = webdriver.Chrome("chromedriver.exe")
time.sleep(2)
driver2.get('https://www.bcci.tv/')
driver2.maximize_window()
time.sleep(2)

# delay = 2
# WebDriverWait(driver2, delay).until(EC.presence_of_element_located((By.CLASS_NAME, 'reference')))
search = driver2.find_element_by_xpath("//li[@class = 'nav-item ml-0']//a")
driver2.get(search.get_attribute('href'))
time.sleep(2)

In [97]:
details = driver2.find_elements_by_xpath("//div[@class = 'fixture-card-top']")

In [121]:
fixtures = []
for i in details:
    fixtures.append(i.text.split("\n"))
    
matches_name = []
matches_date = []
matches_time = []

for j in fixtures[0:5:1]:
    matches_name.append(j[0:1])
    matches_date.append(j[1:2])
    matches_time.append(j[2:3])
    

venues = []
venue = driver2.find_elements_by_xpath("//div[@class = 'fix-place ng-binding ng-scope']")
for k in venue:
    venues.append(k.text)
    
series = []
place = []
for i in venues:
    series.append(i[0:9])
    place.append(i[11:])

In [122]:
#Making DataFrame
df = pd.DataFrame({"Matches_name": matches_name, "Series": series, "Matches_Dates": matches_date, "Matches_Time": matches_time, "Venue": place})
df

,Matches_name,Series,Matches_Dates,Matches_Time,Venue
0,[SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022],1st T20I,[9 JUN 2022],[7:00 PM IST],"Arun Jaitley Stadium, Delhi"
1,[SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022],2nd T20I,[12 JUN 2022],[7:00 PM IST],"Barabati Stadium, Cuttack"
2,[SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022],3rd T20I,[14 JUN 2022],[7:00 PM IST],Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadi...
3,[SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022],4th T20I,[17 JUN 2022],[7:00 PM IST],"Saurashtra Cricket Association Stadium, Rajkot"
4,[SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022],5th T20I,[19 JUN 2022],[7:00 PM IST],"M Chinnaswamy Stadium, Bengaluru"

In [123]:
driver2.close()

3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/

You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [138]:
driver3 = webdriver.Chrome("chromedriver.exe")
time.sleep(2)
driver3.get('https://www.guru99.com/')
driver3.maximize_window()
time.sleep(2)

# delay = 2
# WebDriverWait(driver3, delay).until(EC.presence_of_element_located((By.CLASS_NAME, 'data-lasso-id')))
try:
    search = driver3.find_element_by_xpath("//a[@data-lasso-id='145318']")
    driver3.get(search.get_attribute('href'))
except NoSuchElementException:
    search = driver3.find_element_by_xpath("//a[@data-lasso-id='147434']")
    driver3.get(search.get_attribute('href'))

time.sleep(2)

try:
    search1 = driver3.find_element_by_xpath("//a[@data-lasso-id='182688']")
    driver3.get(search1.get_attribute('href'))
except NoSuchElementException:
    print("close driver and try again")

In [201]:
table = driver3.find_elements_by_xpath("//table[@class = 'table table-striped']/tbody/tr/td")
name= []
description = []
for i in table[0:82:2]:
    name.append(i.text)

for j in table[1:83:2]:
    description.append(j.text)

In [203]:
#Making DataFrame
df = pd.DataFrame({"Exception_Name": name, "Decription": description})
df

,Exception_Name,Decription
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [204]:
driver3.close()

4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
    
You have to find following details:
    
A) Rank

B) State

C) GSDP(18-19)

D) GSDP(17-18)

E) Share(2017)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code

In [234]:
driver4 = webdriver.Chrome("chromedriver.exe")
time.sleep(2)
driver4.get('https://www.statisticstimes.com/')
driver4.maximize_window()
time.sleep(2)

# delay = 2
# WebDriverWait(driver2, delay).until(EC.presence_of_element_located((By.CLASS_NAME, 'reference')))

In [235]:
search = driver4.find_elements_by_xpath("//button[@class = 'dropbtn']")
search[1].text
for i in search:
    if i.text == 'Economy':
        i.click()
        
select = driver4.find_elements_by_xpath("//div[@class = 'dropdown']/div/a")
select[4].click()

In [243]:
select_gdp = driver4.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
select_gdp.click()

In [261]:
table = driver4.find_elements_by_xpath("//table[@class = 'display dataTable']/tbody/tr/td")
#len(table)

In [262]:
rank = []
state = []
GSDP1_19_20 = []
GSDP1_18_19 = []
shares = []
GDP = []
GSDP2_19_20 = []
GSDP2_18_19 = []

for i in table[0:257:8]:
    rank.append(i.text)
    
for i in table[1:258:8]:
    state.append(i.text)
    
for i in table[2:259:8]:
    GSDP1_19_20.append(i.text)
    
for i in table[3:260:8]:
    GSDP1_18_19.append(i.text)
    
for i in table[4:261:8]:
    shares.append(i.text)

    
for i in table[5:262:8]:
    GDP.append(i.text)

    
for i in table[6:263:8]:
    GSDP2_19_20.append(i.text)
    
    
for i in table[7:264:8]:
    GSDP2_18_19.append(i.text)
    
print(len(rank))
print(len(state))
print(len(GSDP1_19_20))
print(len(GSDP1_18_19))
print(len(shares))
print(len(GDP))
print(len(GSDP2_19_20))
print(len(GSDP2_18_19))

33
33
33
33
33
33
33
33

In [267]:
df = pd.DataFrame({'Rank' : rank, 'State' : state, 'GSDP at Current Prices (19-20)' :  GSDP1_19_20, 
                   'GSDP at Current Prices (18-19)' : GSDP1_18_19,
                   'Share' :  shares, 
                   'GDP (2019)' :  GDP,
                  'GSDP at 2011-12 (19-20)' :  GSDP2_19_20, 'GSDP at 2011-12 (18-19)' :  GSDP2_18_19})
df

,Rank,State,GSDP at Current Prices (19-20),GSDP at Current Prices (18-19),Share,GDP (2019),GSDP at 2011-12 (19-20),GSDP at 2011-12 (18-19)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921,-,"2,039,074"
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629,"1,312,929","1,215,307"
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726,"1,166,817","1,123,982"
3,4,Gujarat,-,"1,502,899",7.96%,228.290,-,"1,186,379"
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806,"1,156,039","1,091,077"
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556,"793,223","739,525"
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179,"711,627","677,428"
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083,"672,018","621,301"
8,9,Telangana,"969,604","861,031",4.56%,130.791,"663,258","612,828"
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977,"561,801","522,009"
10,11,Kerala,-,"781,653",4.14%,118.733,-,"559,412"
11,12,Delhi,"856,112","774,870",4.10%,117.703,"634,408","590,569"
12,13,Haryana,"831,610","734,163",3.89%,111.519,"572,240","531,085"
13,14,Bihar,"611,804","530,363",2.81%,80.562,"414,977","375,651"
14,15,Punjab,"574,760","526,376",2.79%,79.957,"418,868","397,669"
15,16,Odisha,"521,275","487,805",2.58%,74.098,"396,499","376,877"
16,17,Assam,-,"315,881",1.67%,47.982,-,"234,048"
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187,"243,477","231,182"
18,19,Jharkhand,"328,598","297,204",1.57%,45.145,"240,036","224,986"
19,20,Uttarakhand,-,"245,895",1.30%,37.351,-,"193,273"
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690,-,"112,755"
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369,"124,403","117,851"
22,23,Goa,"80,449","73,170",0.39%,11.115,"63,408","57,787"
23,24,Tripura,"55,984","49,845",0.26%,7.571,"40,583","36,963"
24,25,Chandigarh,-,"42,114",0.22%,6.397,-,"31,192"
25,26,Puducherry,"38,253","34,433",0.18%,5.230,"25,093","23,013"
26,27,Meghalaya,"36,572","33,481",0.18%,5.086,"26,695","24,682"
27,28,Sikkim,"32,496","28,723",0.15%,4.363,"20,017","18,722"
28,29,Manipur,"31,790","27,870",0.15%,4.233,"20,673","19,300"
29,30,Nagaland,-,"27,283",0.14%,4.144,-,"17,647"
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737,-,"16,676"
31,32,Mizoram,"26,503","22,287",0.12%,3.385,"18,797","16,478"
32,33,Andaman & Nicobar Islands,-,-,-,-,-,-

5. . Scrape the details of trending repositories on Github.com.
Url = https://github.com/

You have to find the following details:
    
A) Repository title

B) Repository description

C) Contributors count

D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [55]:
driver5 = webdriver.Chrome("chromedriver.exe")
time.sleep(2)
driver5.get('https://github.com/')
driver5.maximize_window()
time.sleep(2)

In [57]:
try:
    search = driver5.find_elements_by_xpath("//a[@class = 'lh-condensed-ultra d-block no-underline position-relative Link--primary text-bold py-2']")
    search[1].get_attribute("href")
    for i in search:
        if i.text == 'Explore GitHub':
            i.click()
        
except StaleElementReferenceException:
     driver5.get_attribute("https://github.com/explore")  # if driver not then it goes for manual process

In [58]:
option = driver5.find_elements_by_xpath("//a[@class = 'js-selected-navigation-item d-inline-block py-2 py-md-3 mr-3 mr-md-4 no-underline subnav-link']")

index = 0
for i, element in enumerate(option):
    if element.text == 'Trending':
        index = i
url = option[index].get_attribute('href')

In [59]:
driver5.get(url)

In [162]:
repository = []
repo = driver5.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']//a")
for i in repo:
    repository.append(i.text)   
    
description = []
desc = driver5.find_elements_by_xpath("//p[@class = 'col-9 color-fg-muted my-1 pr-4']")
for j in desc:
    description.append(j.text)

In [164]:
user_url = []
title_tag = driver5.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']/a")
for i in title_tag:
    user_url.append(i.get_attribute('href'))
len(user_url)

language = []
contributors = []
for i in user_url:
    driver5.get(i)

    try : 
        language_tag = driver5.find_elements_by_xpath("//a[@data-ga-click = 'Repository, language stats search click, location:repo overview']")
        temp_lang = []
        for i in language_tag:
            temp_lang.append(i.text.split('\n')[0])
    
        language.append(temp_lang)
    except:
        language.append('-')
        
    try : 
        contributors_tag = driver5.find_element_by_xpath("//h2[@class = 'h4 mb-3']/a/span")
        contributors.append(contributors_tag.text)
    except:
        contributors.append('-')
        
print(len(language))
print(len(contributors))

25
25

In [166]:
df = pd.DataFrame({'Repository' : repository, 'Descriptions' : description, 'languages' :  language, 
                   'Contriubtors_count' : contributors,})
df

,Repository,Descriptions,languages,Contriubtors_count
0,tinygo-org / tinygo,Go compiler for small places. Microcontrollers...,"[Go, Assembly, Makefile, C++, JavaScript, HTML]",27
1,bradtraversy / 50projects50days,"50+ mini web projects using HTML, CSS & JS","[CSS, HTML, JavaScript]",
2,MystenLabs / sui,"Sui, a next-generation smart contract platform...","[Rust, TypeScript, CSS, SCSS, Python, JavaScript]",
3,alibaba / GaiaX,GaiaX dynamic template engine is a lightweight...,"[Rust, Kotlin, Objective-C, C++, CSS, HTML]",16
4,borisdayma / dalle-mini,DALL·E Mini - Generate images from a text prompt,"[Python, Jupyter Notebook]",3
5,papers-we-love / papers-we-love,Papers from the computer science community to ...,[Shell],
6,doocs / source-code-hunter,😱 从源码层面，剖析挖掘互联网行业主流技术的底层实现原理，为广大开发者 “提升技术深度” 提...,[Java],
7,Lissy93 / dashy,🚀 A self-hosted startpage for your server. Eas...,"[Vue, JavaScript, SCSS, HTML, CSS, Dockerfile]",14
8,shimohq / chinese-programmer-wrong-pronunciation,中国程序员容易发音错误的单词,[Python],
9,Nwqda / CVE-2022-26134,[PoC] Atlassian Confluence (CVE-2022-26134) - ...,[Python],
10,ahmedtariq01 / Cloud-DevOps-Learning-Resources,This repo includes Books and imp notes related...,[],-
11,v2fly / v2ray-core,A platform for building proxies to bypass netw...,[Go],56
12,saharmor / dalle-playground,A playground to generate images from any text ...,"[JavaScript, Python, Jupyter Notebook, HTML, D...",2
13,knela96 / Dynamic-Parkour-System,Dynamic Parkour System is a FREE plugin for Un...,[C#],5
14,florinpop17 / app-ideas,A Collection of application ideas which can be...,[],
15,ashishpatel26 / Andrew-NG-Notes,This is Andrew NG Coursera Handwritten Notes.,[Jupyter Notebook],
16,EpicGames / Signup,Information about signing up for a free Epic G...,[],
17,sveltejs / svelte,Cybernetically enhanced web apps,"[TypeScript, Svelte, JavaScript]",
18,PlasmoHQ / plasmo,The browser extension framework,"[TypeScript, JavaScript, HTML]",3
19,arc298 / instagram-scraper,Scrapes an instagram user's photos and videos,"[Python, Dockerfile, Shell]",52
20,iperov / DeepFaceLive,Real-time face swap for PC streaming or video ...,[Python],20
21,Snailclimb / JavaGuide,「Java学习+面试指南」一份涵盖大部分 Java 程序员所需要掌握的核心知识。准备 Jav...,[Java],
22,google / highway,"Performance-portable, length-agnostic SIMD wit...","[C++, C]",12
23,icloud-photos-downloader / icloud_photos_downl...,A command-line tool to download photos from iC...,"[Python, Shell, Dockerfile]",5
24,vuejs / vitepress,Vite & Vue powered static site generator.,"[TypeScript, Vue, CSS, JavaScript]",30

6. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
    
A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [29]:
driver6 = webdriver.Chrome("chromedriver.exe")
time.sleep(2)
driver6.get('https://www.billboard.com/')
driver6.maximize_window()
time.sleep(2)
delay = 20
WebDriverWait(driver6, delay).until(EC.presence_of_element_located((By.CLASS_NAME, 'admz')))

In [30]:
tag = driver6.find_elements_by_xpath("//a[@class = 'c-link  lrv-a-unstyle-link lrv-u-color-brand-primary:hover lrv-a-hover-effect lrv-u-whitespace-nowrap lrv-u-color-grey-dark']")
for i in tag:
    if i.text =='Hot 100':
        url = i.get_attribute('href')
        
driver6.get(url)

In [32]:
rank_tag = driver6.find_elements_by_xpath("//span[@class = 'c-label  a-font-primary-bold-l u-font-size-32@tablet u-letter-spacing-0080@tablet']")
song_name_tag = driver6.find_elements_by_xpath("//li[@class = 'lrv-u-width-100p']/ul/li/h3")

rank = []
song_name = []
peak_pos = []
artist = []
last_week = []
wks_of_chart = []

#-----------------------------rank and song name -----------------------------------
try :    
    for i, song in zip(rank_tag, song_name_tag):
        rank.append(int(i.text))
        song_name.append(song.text)
except:
    rank.append('-')
    song_name.append('-')
        
details_tag = driver6.find_elements_by_xpath("//li[@class = 'lrv-u-width-100p']/ul/li/span")
details_tag[0].text

# --------------------------fetching artist-----------------------------
try:
    for i in details_tag[0::4]:
        artist.append(i.text)
except:
    artist.append('-')

    
# --------------------------- last week ---------------------------------
try:
    for i in details_tag[1::4]:
        last_week.append(i.text)
except:
    last_week.append('-')
    
# -------------------------------peak pos -----------------------------------
try:
    for i in details_tag[2::4]:
        peak_pos.append(i.text)
except:
    peak_pos.append('-')
    
# ------------------------------wks_of_chart ------------------------------

try:
    for i in details_tag[3::4]:
        wks_of_chart.append(i.text)
except:
    wks_of_chart.append('-')

In [33]:
df6 = pd.DataFrame()
df6['Rank'] = rank
df6['Song Name'] = song_name
df6['Artist'] = artist
df6['Last Week Rank'] = last_week
df6['Peak Rank'] = peak_pos
df6['Weeks on Board'] = wks_of_chart
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df6

,Rank,Song Name,Artist,Last Week Rank,Peak Rank,Weeks on Board
0,1,As It Was,Harry Styles,1,1,9
1,2,First Class,Jack Harlow,2,1,8
2,3,Wait For U,Future Featuring Drake & Tems,3,1,5
3,4,About Damn Time,Lizzo,5,4,7
4,5,Heat Waves,Glass Animals,6,1,72
5,6,Big Energy,Latto,7,3,32
6,7,Me Porto Bonito,Bad Bunny & Chencho Corleone,10,7,4
7,8,Running Up That Hill (A Deal With God),Kate Bush,-,8,21
8,9,Late Night Talking,Harry Styles,4,4,2
9,10,Stay,The Kid LAROI & Justin Bieber,12,1,47
10,11,Titi Me Pregunto,Bad Bunny,16,5,4
11,12,Enemy,Imagine Dragons X JID,11,5,28
12,13,Wasted On You,Morgan Wallen,23,9,29
13,14,Moscow Mule,Bad Bunny,17,4,4
14,15,Ghost,Justin Bieber,18,5,36
15,16,Boyfriend,Dove Cameron,28,16,16
16,17,Woman,Doja Cat,19,7,44
17,18,Bad Habits,Ed Sheeran,27,2,49
18,19,Numb Little Bug,Em Beihold,35,19,18
19,20,Super Gremlin,Kodak Black,33,3,30
20,21,You Proof,Morgan Wallen,26,6,3
21,22,True Love,Kanye West & XXXTENTACION,-,22,1
22,23,Take My Name,Parmalee,48,23,9
23,24,Shivers,Ed Sheeran,36,4,38
24,25,Sweetest Pie,Megan Thee Stallion & Dua Lipa,40,15,12
25,26,Party,Bad Bunny & Rauw Alejandro,31,14,4
26,27,Bam Bam,Camila Cabello Featuring Ed Sheeran,37,21,13
27,28,Thats What I Want,Lil Nas X,34,8,37
28,29,Cold Heart (PNAU Remix),Elton John & Dua Lipa,38,7,39
29,30,Despues de La Playa,Bad Bunny,32,6,4
30,31,AA,Walker Hayes,51,28,21
31,32,Trouble With A Heartbreak,Jason Aldean,44,32,11
32,33,Puffin On Zootiez,Future,39,4,5
33,34,Provenza,Karol G,45,25,6
34,35,MAMIII,Becky G X Karol G,47,15,16
35,36,Ojitos Lindos,Bad Bunny & Bomba Estereo,50,26,4
36,37,Cooped Up,Post Malone Featuring Roddy Ricch,43,29,3
37,38,'Til You Can't,Cody Johnson,46,18,34
38,39,N95,Kendrick Lamar,20,3,3
39,40,Something In The Orange,Zach Bryan,42,40,6
40,41,Music For A Sushi Restaurant,Harry Styles,8,8,2
41,42,Matilda,Harry Styles,9,9,2
42,43,Thousand Miles,The Kid LAROI,52,15,6
43,44,She's All I Wanna Be,Tate McRae,60,44,17
44,45,In A Minute,Lil Baby,53,14,8
45,46,Daylight,Harry Styles,13,13,2
46,47,Sleazy Flow,SleazyWorld Go Featuring Lil Baby,-,47,1
47,48,Damn Strait,Scotty McCreery,57,48,9
48,49,Get Into It (Yuh),Doja Cat,58,49,26
49,50,Efecto,Bad Bunny,63,34,4
50,51,Silent Hill,Kendrick Lamar & Kodak Black,49,7,3
51,52,Die Hard,"Kendrick Lamar, Blxst & Amanda Reifer",41,5,3
52,53,Hold My Hand,Lady Gaga,86,53,4
53,54,2step,Ed Sheeran Featuring Lil Baby,64,51,6
54,55,Fall In Love,Bailey Zimmerman,65,55,5
55,56,To The Moon!,JNR CHOI & Sam Tompkins,54,38,14
56,57,Slow Down Summer,Thomas Rhett,66,43,15
57,58,Little Freak,Harry Styles,14,14,2
58,59,See Wat I'm Sayin,Moneybagg Yo,-,59,1
59,60,Die Young,Sleepy Hallow Featuring 347aidan,-,60,1
60,61,Grapejuice,Harry Styles,15,15,2
61,62,Un Ratito,Bad Bunny,56,16,4
62,63,Tarot,Bad Bunny & Jhay Cortez,55,18,4
63,64,When You're Gone,Shawn Mendes,67,38,9
64,65,Satellite,Harry Styles,21,21,2
65,66,Like I Love Country Music,Kane Brown,74,66,2
66,67,What Happened To Virgil,Lil Durk Featuring Gunna,69,22,12
67,68,Never Say Never,Cole Swindell / Lainey Wilson,68,27,20
68,69,Thought You Should Know,Morgan Wallen,62,12,4
69,70,If I Was A Cowboy,Miranda Lambert,75,53,18
70,71,Potion,"Calvin Harris, Dua Lipa & Young Thug",-,71,1
71,72,Hotel Lobby (Unc And Phew),Quavo & Takeoff,59,59,2
72,73,Right On,Lil Baby,71,13,8
73,74,Freaky Deaky,Tyga X Doja Cat,72,43,14
74,75,Cinema,Harry Styles,22,22,2
75,76,Keep Driving,Harry Styles,25,25,2
76,77,Daydreaming,Harry Styles,24,24,2
77,78,Yo No Soy Celoso,Bad Bunny,70,22,4
78,79,Flower Shops,ERNEST Featuring Morgan Wallen,82,64,19
79,80,She Likes It,Russell Dickerson & Jake Scott,90,80,9
80,81,Love Of My Life,Harry Styles,29,29,2
81,82,Ghost Story,Carrie Underwood,-,72,2
82,83,Rich Spirit,Kendrick Lamar,61,13,3
83,84,La Corriente,Bad Bunny & Tony Dize,80,32,4
84,85,Neverita,Bad Bunny,77,31,4
85,86,She Had Me At Heads Carolina,Cole Swindell,-,86,1
86,87,Sunroof,Nicky Youre & dazy,-,87,1
87,88,Boyfriends,Harry Styles,30,30,2
88,89,Circles Around This Town,Maren Morris,88,52,19
89,90,Dua Lipa,Jack Harlow,76,21,4
90,91,F.N.F. (Let's Go),Hitkidd & Glorilla,-,91,1
91,92,Handsomer,Russ Featuring Ktlyn,-,40,10
92,93,I'm On One,Future Featuring Drake,83,11,5
93,94,DFMU,Ella Mai,99,94,2
94,95,Andrea,Bad Bunny & Buscabulla,87,51,4
95,96,Love You Better,Future,84,12,5
96,97,Wild Hearts,Keith Urban,-,97,1
97,98,Last Night Lonely,Jon Pardi,-,98,1
98,99,7500 OBO,Tim McGraw,-,99,1
99,100,Until I Found You,Stephen Sanchez,-,100,1

In [43]:
#driver6.close()

7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
    
You have to find the following details:
    
A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [48]:
driver7 = webdriver.Chrome("chromedriver.exe")
time.sleep(2)
driver7.get('https://www.naukri.com/')
driver7.maximize_window()
time.sleep(10)

In [49]:
try:
    driver7.find_element_by_xpath("//span[@class = 'fr geoLocBtn later']").click()
except:
    driver7.get("https://www.naukri.com/hr-recruiters-consultants") # if we not get url then goes for manual

In [53]:
search_jobs = driver7.find_element_by_xpath("//input[@class = 'sugInp']")
search_jobs.send_keys('Data Science')
search_jobs.send_keys(Keys.ENTER)

In [64]:
names = []
designations = []
locations = []
skills = []
companies = []
name = driver7.find_elements_by_xpath("//span[@class = 'fl ellipsis']")
designation = driver7.find_elements_by_xpath("//span[@class = 'ellipsis clr']")
skill = driver7.find_elements_by_xpath("//div[@class = 'hireSec highlightable']")
location = driver7.find_elements_by_xpath("//small[@class = 'ellipsis']")
company = driver7.find_elements_by_xpath("//span[@class = 'ellipsis clr']")



for name, designation, location, skill, company in zip(name, designation, location, skill, company):
    names.append(name.text)
    designations.append(designation.text)
    skills.append(skill.text)
    locations.append(location.text)
    companies.append(company.text)
    
print(len(names))
print(len(designations))
print(len(skills))
print(len(locations))
print(len(companies))

48
48
48
48
48

In [65]:
df7 = pd.DataFrame()
df7['Name'] = names
df7['Designations'] = designations
df7['Companies'] = companies
df7['Locations'] = locations
df7['Skills_req'] = skills
df7['Companies'] = companies
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df7

,Name,Designations,Companies,Locations,Skills_req
0,Aakash Harit,HR Manager,HR Manager,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Company Recruiter,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,Company HR,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Company Recruiter,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,Founder CEO,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Recruitment Lead Consultant,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,Programme Manager,Chennai,Data Science
7,Balu Ramesh,HR Administrator,HR Administrator,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Director,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,Human Resource,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Priyanka Akiri,HR Manager,HR Manager,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
11,Kalpana Dumpala,Executive Hiring,Executive Hiring,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
12,Mubarak,Company HR,Company HR,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
13,Kushal Rastogi,Company HR,Company HR,Mumbai,"Office Administration, Hr Administration, tele..."
14,Mahesh Babu Channa,HR Team Lead,HR Team Lead,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
15,Kapil Devang,HR Manager,HR Manager,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
16,Dhruv Dev Dubey,Company Recruitment Head,Company Recruitment Head,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
17,Sakshi Chhikara,Assistant Manager HR,Assistant Manager HR,Chandigarh,"React.js, Data Science, Java, Front End, Busin..."
18,Ruchi Dhote,Senior Executive Talent Acquisition,Senior Executive Talent Acquisition,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
19,Manisha Yadav,HR Executive,HR Executive,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
20,Riya Rajesh,Manager Talent Acquisition,Manager Talent Acquisition,Cochin,Data Science
21,Rashmi Bhattacharjee,HR Head,HR Head,Delhi,"Corporate Sales, Software Development, Softwar..."
22,Faizan Kareem,HR MANAGER,HR MANAGER,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
23,Rithika dadwal,HR Recruiter,HR Recruiter,Pune,"Data Science, Machine Learning, Python, R, Dee..."
24,Sandhya Khandagale,HR Recruiter,HR Recruiter,Pune,"Big Data, Data Science, Artificial Intelligenc..."
25,Shaun Rao,Manager Human Resources,Manager Human Resources,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
26,Azahar Shaikh,Company Recruiter,Company Recruiter,Pune,"Data Science, Artificial Intelligence, Machine..."
27,Manas,Lead Talent acquisition,Lead Talent acquisition,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
28,kumar,Proprietor,Proprietor,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
29,Sunil Vedula,CEO,CEO,Delhi,"Signal Processing, Machine Learning, Neural Ne..."
30,Rajat Kumar,Founder CEO,Founder CEO,Mysoru / Mysore,"Web Technologies, Project Management, Software..."
31,Jayanth N,Project Manager,Project Manager,Hyderabad / Secunderabad,"Data Analytics, Managed Services, Team Leading..."
32,Avodha,Business Development Associate,Business Development Associate,Hyderabad / Secunderabad,"Ethical Hacking, Security Operations Center, S..."
33,SREEDHAR,Recruitment Consultant,Recruitment Consultant,Bengaluru / Bangalore,"Data Science, Machine Learning, Big Data Analy..."
34,Priya Khare,Senior Manager,Senior Manager,New Delhi,"Data Science, Artificial Intelligence, analyti..."
35,Amit Sharma,Consultant,Consultant,Chennai,"Machine Learning, Artificial Intelligence, Dat..."
36,Kanan,senior technology instructor,senior technology instructor,Aligarh,"C, C++, Artificial Intelligence, Python, Php, ..."
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,HR Recruiter/HR Excutive,Salt Lake City,"Relationship Management, Retail Sales, Private..."
38,Brad,"Manager, Technical Recruiting","Manager, Technical Recruiting",Pune,"Data Science, Software Engineering"
39,Rutuja Pawar,Technical Recruiter,Technical Recruiter,Bengaluru / Bangalore,"Data Science, Big Data Analytics, Digital Mark..."
40,Madhusudhan Sridhar,Erp Implementer,Erp Implementer,Mumbai,"Data Science, Recruitment, Salary"
41,Ankit Sinha,Head Analytics,Head Analytics,Indore,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
42,Gaurav Chouhan,Chief Technical Officer,Chief Technical Officer,Bengaluru / Bangalore,"Software Development, Business Intelligence, B..."
43,Rashi Kacker,Sr Product Manager,Sr Product Manager,MYSORE,"Data Science, Node.js, Angularjs"
44,Ashwini,Director Global Delivery,Director Global Delivery,Hyderabad / Secunderabad,"Data Science, Media Marketing, Resource Planni..."
45,Balaji Kolli,Co Founder,Co Founder,Bengaluru / Bangalore,"Data Analysis, Learning, Data Science, Compute..."
46,Rajani Nagaraj,HR Manager,HR Manager,Mumbai,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
47,ROHIT Kumar,Architect,Architect,Ghaziabad,"Software Development, Core Java, Unit Testing,..."

8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
    
A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [66]:
driver8 = webdriver.Chrome("chromedriver.exe")
time.sleep(2)
driver8.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')
driver8.maximize_window()
time.sleep(10)

In [115]:
try:
    table = driver8.find_elements_by_xpath("//table[@class = 'in-article sortable']/tbody/tr/td")
except:
    print('Not found')

ranks = []
titles = []
authors = []
volumes = []
publishers = []
genres = []

for i in table[0::6]:
    ranks.append((i.text))
    
for i in table[1::6]:
    titles.append(i.text)
    
for i in table[2::6]:
    authors.append(i.text)
    
for i in table[3::6]:
    volumes.append(i.text)
    
for i in table[4::6]:
    publishers.append(i.text)

for i in table[5::6]:
    genres.append(i.text)
    
print(len(ranks))
print(len(titles))
print(len(authors))
print(len(volumes))
print(len(publishers))
print(len(genres))

100
100
100
100
100
100

In [117]:
df8 = pd.DataFrame()
df8['Rank'] = ranks
df8['Title'] = titles
df8['Author'] = authors
df8['Volumne'] = volumes
df8['Publisher'] = publishers
df8['Genre'] = genres
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df8

,Rank,Title,Author,Volumne,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
5,6,Harry Potter and the Goblet of Fire,"Rowling, J.K.","3,583,215",Bloomsbury,Children's Fiction
6,7,Harry Potter and the Chamber of Secrets,"Rowling, J.K.","3,484,047",Bloomsbury,Children's Fiction
7,8,Harry Potter and the Prisoner of Azkaban,"Rowling, J.K.","3,377,906",Bloomsbury,Children's Fiction
8,9,Angels and Demons,"Brown, Dan","3,193,946",Transworld,"Crime, Thriller & Adventure"
9,10,Harry Potter and the Half-blood Prince:Childre...,"Rowling, J.K.","2,950,264",Bloomsbury,Children's Fiction
10,11,Fifty Shades Darker,"James, E. L.","2,479,784",Random House,Romance & Sagas
11,12,Twilight,"Meyer, Stephenie","2,315,405","Little, Brown Book",Young Adult Fiction
12,13,"Girl with the Dragon Tattoo,The:Millennium Tri...","Larsson, Stieg","2,233,570",Quercus,"Crime, Thriller & Adventure"
13,14,Fifty Shades Freed,"James, E. L.","2,193,928",Random House,Romance & Sagas
14,15,"Lost Symbol,The","Brown, Dan","2,183,031",Transworld,"Crime, Thriller & Adventure"
15,16,New Moon,"Meyer, Stephenie","2,152,737","Little, Brown Book",Young Adult Fiction
16,17,Deception Point,"Brown, Dan","2,062,145",Transworld,"Crime, Thriller & Adventure"
17,18,Eclipse,"Meyer, Stephenie","2,052,876","Little, Brown Book",Young Adult Fiction
18,19,"Lovely Bones,The","Sebold, Alice","2,005,598",Pan Macmillan,General & Literary Fiction
19,20,"Curious Incident of the Dog in the Night-time,The","Haddon, Mark","1,979,552",Random House,General & Literary Fiction
20,21,Digital Fortress,"Brown, Dan","1,928,900",Transworld,"Crime, Thriller & Adventure"
21,22,"Short History of Nearly Everything,A","Bryson, Bill","1,852,919",Transworld,Popular Science
22,23,"Girl Who Played with Fire,The:Millennium Trilogy","Larsson, Stieg","1,814,784",Quercus,"Crime, Thriller & Adventure"
23,24,Breaking Dawn,"Meyer, Stephenie","1,787,118","Little, Brown Book",Young Adult Fiction
24,25,"Very Hungry Caterpillar,The:The Very Hungry Ca...","Carle, Eric","1,783,535",Penguin,Picture Books
25,26,"Gruffalo,The","Donaldson, Julia","1,781,269",Pan Macmillan,Picture Books
26,27,Jamie's 30-Minute Meals,"Oliver, Jamie","1,743,266",Penguin,Food & Drink: General
27,28,"Kite Runner,The","Hosseini, Khaled","1,629,119",Bloomsbury,General & Literary Fiction
28,29,One Day,"Nicholls, David","1,616,068",Hodder & Stoughton,General & Literary Fiction
29,30,"Thousand Splendid Suns,A","Hosseini, Khaled","1,583,992",Bloomsbury,General & Literary Fiction
30,31,"Girl Who Kicked the Hornets' Nest,The:Millenni...","Larsson, Stieg","1,555,135",Quercus,"Crime, Thriller & Adventure"
31,32,"Time Traveler's Wife,The","Niffenegger, Audrey","1,546,886",Random House,General & Literary Fiction
32,33,Atonement,"McEwan, Ian","1,539,428",Random House,General & Literary Fiction
33,34,Bridget Jones's Diary:A Novel,"Fielding, Helen","1,508,205",Pan Macmillan,General & Literary Fiction
34,35,"World According to Clarkson,The","Clarkson, Jeremy","1,489,403",Penguin,Humour: Collections & General
35,36,Captain Corelli's Mandolin,"Bernieres, Louis de","1,352,318",Random House,General & Literary Fiction
36,37,"Sound of Laughter,The","Kay, Peter","1,310,207",Random House,Autobiography: General
37,38,Life of Pi,"Martel, Yann","1,310,176",Canongate,General & Literary Fiction
38,39,Billy Connolly,"Stephenson, Pamela","1,231,957",HarperCollins,Biography: The Arts
39,40,"Child Called It,A","Pelzer, Dave","1,217,712",Orion,Autobiography: General
40,41,"Gruffalo's Child,The","Donaldson, Julia","1,208,711",Pan Macmillan,Picture Books
41,42,Angela's Ashes:A Memoir of a Childhood,"McCourt, Frank","1,204,058",HarperCollins,Autobiography: General
42,43,Birdsong,"Faulks, Sebastian","1,184,967",Random House,General & Literary Fiction
43,44,Northern Lights:His Dark Materials S.,"Pullman, Philip","1,181,503",Scholastic Ltd.,Young Adult Fiction
44,45,Labyrinth,"Mosse, Kate","1,181,093",Orion,General & Literary Fiction
45,46,Harry Potter and the Half-blood Prince,"Rowling, J.K.","1,153,181",Bloomsbury,Science Fiction & Fantasy
46,47,"Help,The","Stockett, Kathryn","1,132,336",Penguin,General & Literary Fiction
47,48,Man and Boy,"Parsons, Tony","1,130,802",HarperCollins,General & Literary Fiction
48,49,Memoirs of a Geisha,"Golden, Arthur","1,126,337",Random House,General & Literary Fiction
49,50,"No.1 Ladies' Detective Agency,The:No.1 Ladies'...","McCall Smith, Alexander","1,115,549","Little, Brown Book","Crime, Thriller & Adventure"
50,51,"Island,The","Hislop, Victoria","1,108,328",Headline,General & Literary Fiction
51,52,"PS, I Love You","Ahern, Cecelia","1,107,379",HarperCollins,General & Literary Fiction
52,53,You are What You Eat:The Plan That Will Change...,"McKeith, Gillian","1,104,403",Penguin,Fitness & Diet
53,54,"Shadow of the Wind,The","Zafon, Carlos Ruiz","1,092,349",Orion,General & Literary Fiction
54,55,"Tales of Beedle the Bard,The","Rowling, J.K.","1,090,847",Bloomsbury,Children's Fiction
55,56,"Broker,The","Grisham, John","1,087,262",Random House,"Crime, Thriller & Adventure"
56,57,"Dr. Atkins' New Diet Revolution:The No-hunger,...","Atkins, Robert C.","1,054,196",Random House,Fitness & Diet
57,58,"Subtle Knife,The:His Dark Materials S.","Pullman, Philip","1,037,160",Scholastic Ltd.,Young Adult Fiction
58,59,"Eats, Shoots and Leaves:The Zero Tolerance App...","Truss, Lynne","1,023,688",Profile Books Group,Usage & Writing Guides
59,60,Delia's How to Cook:(Bk.1),"Smith, Delia","1,015,956",Random House,Food & Drink: General
60,61,Chocolat,"Harris, Joanne","1,009,873",Transworld,General & Literary Fiction
61,62,"Boy in the Striped Pyjamas,The","Boyne, John","1,004,414",Random House Childrens Books G,Young Adult Fiction
62,63,My Sister's Keeper,"Picoult, Jodi","1,003,780",Hodder & Stoughton,General & Literary Fiction
63,64,"Amber Spyglass,The:His Dark Materials S.","Pullman, Philip","1,002,314",Scholastic Ltd.,Young Adult Fiction
64,65,To Kill a Mockingbird,"Lee, Harper","998,213",Random House,General & Literary Fiction
65,66,"Men are from Mars, Women are from Venus:A Prac...","Gray, John","992,846",HarperCollins,Popular Culture & Media: General Interest
66,67,Dear Fatty,"French, Dawn","986,753",Random House,Autobiography: The Arts
67,68,"Short History of Tractors in Ukrainian,A","Lewycka, Marina","986,115",Penguin,General & Literary Fiction
68,69,Hannibal,"Harris, Thomas","970,509",Random House,"Crime, Thriller & Adventure"
69,70,"Lord of the Rings,The","Tolkien, J. R. R.","967,466",HarperCollins,Science Fiction & Fantasy
70,71,Stupid White Men:...and Other Sorry Excuses fo...,"Moore, Michael","963,353",Penguin,Current Affairs & Issues
71,72,"Interpretation of Murder,The","Rubenfeld, Jed","962,515",Headline,"Crime, Thriller & Adventure"
72,73,Sharon Osbourne Extreme:My Autobiography,"Osbourne, Sharon","959,496","Little, Brown Book",Autobiography: The Arts
73,74,"Alchemist,The:A Fable About Following Your Dream","Coelho, Paulo","956,114",HarperCollins,General & Literary Fiction
74,75,At My Mother's Knee ...:and Other Low Joints,"O'Grady, Paul","945,640",Transworld,Autobiography: The Arts
75,76,Notes from a Small Island,"Bryson, Bill","931,312",Transworld,Travel Writing
76,77,"Return of the Naked Chef,The","Oliver, Jamie","925,425",Penguin,Food & Drink: General
77,78,Bridget Jones: The Edge of Reason,"Fielding, Helen","924,695",Pan Macmillan,General & Literary Fiction
78,79,Jamie's Italy,"Oliver, Jamie","906,968",Penguin,National & Regional Cuisine
79,80,I Can Make You Thin,"McKenna, Paul","905,086",Transworld,Fitness & Diet
80,81,Down Under,"Bryson, Bill","890,847",Transworld,Travel Writing
81,82,"Summons,The","Grisham, John","869,671",Random House,"Crime, Thriller & Adventure"
82,83,Small Island,"Levy, Andrea","869,659",Headline,General & Literary Fiction
83,84,Nigella Express,"Lawson, Nigella","862,602",Random House,Food & Drink: General
84,85,Brick Lane,"Ali, Monica","856,540",Transworld,General & Literary Fiction
85,86,"Memory Keeper's Daughter,The","Edwards, Kim","845,858",Penguin,General & Literary Fiction
86,87,Room on the Broom,"Donaldson, Julia","842,535",Pan Macmillan,Picture Books
87,88,About a Boy,"Hornby, Nick","828,215",Penguin,General & Literary Fiction
88,89,My Booky Wook,"Brand, Russell","820,563",Hodder & Stoughton,Autobiography: The Arts
89,90,"God Delusion,The","Dawkins, Richard","816,907",Transworld,Popular Science
90,91,"""Beano"" Annual,The",0,"816,585",D.C. Thomson,Children's Annuals
91,92,White Teeth,"Smith, Zadie","815,586",Penguin,General & Literary Fiction
92,93,"House at Riverton,The","Morton, Kate","814,370",Pan Macmillan,General & Literary Fiction
93,94,"Book Thief,The","Zusak, Markus","809,641",Transworld,General & Literary Fiction
94,95,Nights of Rain and Stars,"Binchy, Maeve","808,900",Orion,General & Literary Fiction
95,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

####

9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
    
A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [118]:
driver9 = webdriver.Chrome("chromedriver.exe")
time.sleep(2)
driver9.get('https://www.imdb.com/list/ls095964455/')
driver9.maximize_window()
time.sleep(10)

In [262]:
names = []
years = []
votes = []
genres = []
run_time = []
ratings = []

name = driver9.find_elements_by_xpath("//h3[@class = 'lister-item-header']/a")
for i in name:
    names.append(i.text)
 

year = driver9.find_elements_by_xpath("//span[@class = 'lister-item-year text-muted unbold']")
for i in year:
    years.append((i.text))


vote = driver9.find_elements_by_xpath("//span[@name = 'nv']")
for i in vote:
    votes.append(i.text)
    
genre = driver9.find_elements_by_xpath("//span[@class = 'genre']")
for i in genre:
    genres.append(i.text)
    
time = driver9.find_elements_by_xpath("//span[@class = 'runtime']")
for i in time:
    run_time.append(i.text)
    
rating = driver9.find_elements_by_xpath("//div[@class = 'ipl-rating-widget']/div/span")
for i in rating:
    ratings.append(i.text)
    
print(len(names))
print(len(years))
print(len(votes))
print(len(genres))
print(len(run_time))
print(len(ratings[1::2]))

100
100
100
100
100
100

In [265]:
df9 = pd.DataFrame()
df9['Movie_Names'] = names
df9['Year'] = years
df9['Run_Time'] = run_time
df9['Ratings'] = ratings[1::2]
df9['Genres'] = genres
df9['Votes'] = votes
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df9

,Movie_Names,Year,Run_Time,Ratings,Genres,Votes
0,Game of Thrones,(2011–2019),57 min,9.2,"Action, Adventure, Drama","1,992,919"
1,Stranger Things,(2016– ),51 min,8.7,"Drama, Fantasy, Horror","1,026,346"
2,The Walking Dead,(2010–2022),44 min,8.2,"Drama, Horror, Thriller","948,810"
3,13 Reasons Why,(2017–2020),60 min,7.5,"Drama, Mystery, Thriller","283,475"
4,The 100,(2014–2020),43 min,7.6,"Drama, Mystery, Sci-Fi","243,265"
5,Orange Is the New Black,(2013–2019),59 min,8.1,"Comedy, Crime, Drama","296,386"
6,Riverdale,(2017–2023),45 min,6.7,"Crime, Drama, Mystery","139,879"
7,Grey's Anatomy,(2005– ),41 min,7.6,"Drama, Romance","295,493"
8,The Flash,(2014– ),43 min,7.6,"Action, Adventure, Drama","338,191"
9,Arrow,(2012–2020),42 min,7.5,"Action, Adventure, Crime","426,360"
10,Money Heist,(2017–2021),70 min,8.2,"Action, Crime, Drama","457,371"
11,The Big Bang Theory,(2007–2019),22 min,8.2,"Comedy, Romance","784,775"
12,Black Mirror,(2011–2019),60 min,8.8,"Drama, Mystery, Sci-Fi","519,414"
13,Sherlock,(2010–2017),88 min,9.1,"Crime, Drama, Mystery","895,467"
14,Vikings,(2013–2020),44 min,8.5,"Action, Adventure, Drama","511,072"
15,Pretty Little Liars,(2010–2017),44 min,7.4,"Drama, Mystery, Romance","163,616"
16,The Vampire Diaries,(2009–2017),43 min,7.7,"Drama, Fantasy, Horror","311,872"
17,American Horror Story,(2011– ),60 min,8,"Drama, Horror, Sci-Fi","307,836"
18,Breaking Bad,(2008–2013),49 min,9.5,"Crime, Drama, Thriller","1,743,969"
19,Lucifer,(2016–2021),42 min,8.1,"Crime, Drama, Fantasy","309,545"
20,Supernatural,(2005–2020),44 min,8.5,"Drama, Fantasy, Horror","430,265"
21,Prison Break,(2005–2017),44 min,8.3,"Action, Crime, Drama","518,904"
22,How to Get Away with Murder,(2014–2020),43 min,8.1,"Crime, Drama, Mystery","147,348"
23,Teen Wolf,(2011–2017),41 min,7.7,"Action, Drama, Fantasy","143,353"
24,The Simpsons,(1989– ),22 min,8.7,"Animation, Comedy","396,259"
25,Once Upon a Time,(2011–2018),60 min,7.7,"Adventure, Fantasy, Romance","220,902"
26,Narcos,(2015–2017),49 min,8.8,"Biography, Crime, Drama","406,525"
27,Daredevil,(2015–2018),54 min,8.6,"Action, Crime, Drama","421,880"
28,Friends,(1994–2004),22 min,8.9,"Comedy, Romance","954,819"
29,How I Met Your Mother,(2005–2014),22 min,8.3,"Comedy, Romance","664,415"
30,Suits,(2011–2019),44 min,8.5,"Comedy, Drama","397,355"
31,Mr. Robot,(2015–2019),49 min,8.6,"Crime, Drama, Thriller","375,306"
32,The Originals,(2013–2018),45 min,8.3,"Drama, Fantasy, Horror","132,139"
33,Supergirl,(2015–2021),43 min,6.2,"Action, Adventure, Drama","122,231"
34,Gossip Girl,(2007–2012),42 min,7.4,"Drama, Romance","170,254"
35,Sense8,(2015–2018),60 min,8.2,"Drama, Mystery, Sci-Fi","151,982"
36,Gotham,(2014–2019),42 min,7.8,"Action, Crime, Drama","226,714"
37,Westworld,(2016– ),62 min,8.6,"Drama, Mystery, Sci-Fi","477,588"
38,Jessica Jones,(2015–2019),56 min,7.9,"Action, Crime, Drama","209,784"
39,Modern Family,(2009–2020),22 min,8.5,"Comedy, Drama, Romance","411,663"
40,Rick and Morty,(2013– ),23 min,9.2,"Animation, Adventure, Comedy","477,912"
41,Shadowhunters,(2016–2019),42 min,6.4,"Action, Drama, Fantasy","61,403"
42,The End of the F***ing World,(2017–2019),25 min,8.1,"Adventure, Comedy, Crime","179,233"
43,House of Cards,(2013–2018),51 min,8.7,Drama,"495,360"
44,Dark,(2017–2020),60 min,8.7,"Crime, Drama, Mystery","357,259"
45,Elite,(2018– ),60 min,7.4,"Crime, Drama, Thriller","73,903"
46,Sex Education,(2019– ),45 min,8.4,"Comedy, Drama","262,223"
47,Shameless,(2011–2021),46 min,8.6,"Comedy, Drama","231,209"
48,New Girl,(2011–2018),22 min,7.7,"Comedy, Romance","217,165"
49,Agents of S.H.I.E.L.D.,(2013–2020),45 min,7.5,"Action, Adventure, Drama","214,159"
50,You,(2018– ),45 min,7.7,"Crime, Drama, Romance","227,202"
51,Dexter,(2006–2013),53 min,8.7,"Crime, Drama, Mystery","713,006"
52,Fear the Walking Dead,(2015– ),44 min,6.8,"Drama, Horror, Sci-Fi","127,392"
53,Family Guy,(1999– ),22 min,8.2,"Animation, Comedy","328,599"
54,The Blacklist,(2013– ),43 min,8,"Crime, Drama, Mystery","240,094"
55,Lost,(2004–2010),44 min,8.4,"Adventure, Drama, Fantasy","538,089"
56,Peaky Blinders,(2013–2022),60 min,8.8,"Crime, Drama","491,444"
57,House,(2004–2012),44 min,8.7,"Drama, Mystery","449,949"
58,Quantico,(2015–2018),42 min,6.6,"Crime, Drama, Mystery","60,421"
59,Orphan Black,(2013–2017),44 min,8.3,"Drama, Sci-Fi, Thriller","109,104"
60,Homeland,(2011–2020),55 min,8.3,"Crime, Drama, Mystery","335,851"
61,Blindspot,(2015–2020),42 min,7.3,"Action, Crime, Drama","72,611"
62,DC's Legends of Tomorrow,(2016–2022),42 min,6.7,"Action, Adventure, Drama","103,032"
63,The Handmaid's Tale,(2017– ),60 min,8.4,"Drama, Sci-Fi, Thriller","217,665"
64,Chilling Adventures of Sabrina,(2018–2020),60 min,7.4,"Drama, Fantasy, Horror","90,848"
65,The Good Doctor,(2017– ),41 min,8.1,Drama,"89,628"
66,Jane the Virgin,(2014–2019),60 min,7.9,Comedy,"48,153"
67,Glee,(2009–2015),44 min,6.8,"Comedy, Drama, Music","145,943"
68,South Park,(1997– ),22 min,8.7,"Animation, Comedy","360,819"
69,Brooklyn Nine-Nine,(2013–2021),22 min,8.4,"Comedy, Crime","295,846"
70,Under the Dome,(2013–2015),43 min,6.5,"Drama, Mystery, Sci-Fi","105,602"
71,The Umbrella Academy,(2019– ),60 min,8,"Action, Adventure, Comedy","205,503"
72,True Detective,(2014–2019),55 min,8.9,"Crime, Drama, Mystery","549,046"
73,The OA,(2016–2019),60 min,7.8,"Drama, Fantasy, Mystery","102,439"
74,Desperate Housewives,(2004–2012),45 min,7.6,"Comedy, Drama, Mystery","126,350"
75,Better Call Saul,(2015–2022),46 min,8.8,"Crime, Drama","417,990"
76,Bates Motel,(2013–2017),45 min,8.2,"Drama, Horror, Mystery","105,708"
77,The Punisher,(2017–2019),53 min,8.5,"Action, Crime, Drama","221,986"
78,Atypical,(2017–2021),30 min,8.3,"Comedy, Drama","83,965"
79,Dynasty,(2017–2022),42 min,7.2,Drama,"21,320"
80,This Is Us,(2016–2022),45 min,8.7,"Comedy, Drama, Romance","136,668"
81,The Good Place,(2016–2020),22 min,8.2,"Comedy, Drama, Fantasy","150,098"
82,Iron Fist,(2017–2018),55 min,6.4,"Action, Adventure, Crime","127,645"
83,The Rain,(2018–2020),45 min,6.3,"Drama, Sci-Fi, Thriller","36,035"
84,Mindhunter,(2017–2019),60 min,8.6,"Crime, Drama, Mystery","270,898"
85,Revenge,(2011–2015),44 min,7.8,"Drama, Mystery, Thriller","118,994"
86,Luke Cage,(2016–2018),55 min,7.3,"Action, Crime, Drama","128,060"
87,Scandal,(2012–2018),43 min,7.7,"Drama, Thriller","72,675"
88,The Defenders,(2017),50 min,7.2,"Action, Adventure, Crime","104,082"
89,Big Little Lies,(2017–2019),60 min,8.5,"Crime, Drama, Mystery","190,133"
90,Insatiable,(2018–2019),45 min,6.5,"Comedy, Drama, Thriller","27,533"
91,The Mentalist,(2008–2015),43 min,8.1,"Crime, Drama, Mystery","180,512"
92,The Crown,(2016– ),58 min,8.7,"Biography, Drama, History","191,969"
93,Chernobyl,(2019),330 min,9.4,"Drama, History, Thriller","702,222"
94,iZombie,(2015–2019),42 min,7.8,"Comedy, Crime, Drama","66,719"
95,Reign,(2013–2017),42 min,7.4,"Drama, Fantasy","48,831"
96,A Series of Unfortunate Events,(2017–2019),50 min,7.8,"Adventure, Comedy, Drama","59,499"
97,Criminal Minds,(2005–2020),42 min,8.1,"Crime, Drama, Mystery","190,172"
98,Scream: The TV Series,(2015–2019),45 min,7.1,"Comedy, Crime, Drama","40,265"
99,The Haunting of Hill House,(2018),572 min,8.6,"Drama, Horror, Mystery","228,453"

In [266]:
#driver9.close()

####

10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
    
A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code

In [2]:
driver10 = webdriver.Chrome("chromedriver.exe")
time.sleep(2)
driver10.get('https://archive.ics.uci.edu/ml/index.php')
driver10.maximize_window()
time.sleep(10)

In [5]:
search = driver10.find_element_by_xpath("//span[@class = 'normal']/b/a")
driver10.get(search.get_attribute('href'))

In [30]:
dataset = []  # Dataset names
dataset_url = driver10.find_elements_by_xpath("//p[@class = 'normal']/b/a")
for i in dataset_url:
    dataset.append(i.text)

In [28]:
url = []  # dataset urls
for i in dataset_url:
    url.append(i.get_attribute("href"))

In [70]:
task = []
data_type = []
attribute_type = []
instances = []
attribute = []
year = []


for j in url:
    driver10.get(j)
    time.sleep(2)
    # --------------------------------Attribute type ----------------------------------
    try:
        attribute_type_tag = driver10.find_elements_by_xpath("//table[@border = 1]/tbody/tr/td/p")
        attribute_type.append(attribute_type_tag[7].text)

    except:
        attribute_type.append('-')
    
    # --------------------------------data Type --------------------------------------
    try:  
        data_type_tag = driver10.find_elements_by_xpath("//table[@border = 1]/tbody/tr/td/p")
        data_type.append(data_type_tag[1].text)

    except:
        data_type.append('-')

    #  ----------------------------------------- Task --------------------------------------
    try:  
        task_tag = driver10.find_elements_by_xpath("//table[@border = 1]/tbody/tr/td/p")
        task.append(task_tag[13].text)

    except:
        task.append('-')

    # ------------------------------------------ Instances --------------------------------------
    try:  
        instances_tag = driver10.find_elements_by_xpath("//table[@border = 1]/tbody/tr/td/p")
        instances.append(instances_tag[3].text)

    except:
        instances.append('-')
    
       # ------------------------------------ No. of Attributes  --------------------------
    
    try:  
        attribute_tag = driver10.find_elements_by_xpath("//table[@border = 1]/tbody/tr/td/p")
        attribute.append(attribute_tag[9].text)

    except:
        attribute.append('-')
        
        
       # ------------------------------------year   ------------------------------------
    try:  
        year_tag = driver10.find_elements_by_xpath("//table[@border = 1]/tbody/tr/td/p")
        year.append(year_tag[11].text.split('-')[0])

    except:
        year.append('-')

In [78]:
df10 = pd.DataFrame()
df10['Dataset Name'] =  dataset[:100]
df10['Data Type'] = data_type[:100]
df10['Task'] =  task[:100]
df10['Attribute Type'] =  attribute_type[:100]
df10['No. of Instances'] = instances[:100]
df10['No. of Attributes'] =   attribute[:100]
df10['Year'] =  year[:100]
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df10

,Dataset Name,Data Type,Task,Attribute Type,No. of Instances,No. of Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,N/A
3,Anonymous Microsoft Web Data,N/A,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
5,Artificial Characters,Multivariate,Classification,"Categorical, Integer, Real",6000,7,1992
6,Audiology (Original),Multivariate,Classification,Categorical,226,N/A,1987
7,Audiology (Standardized),Multivariate,Classification,Categorical,226,69,1992
8,Auto MPG,Multivariate,Regression,"Categorical, Real",398,8,1993
9,Automobile,Multivariate,Regression,"Categorical, Integer, Real",205,26,1987
10,Badges,"Univariate, Text",Classification,N/A,294,1,1994
11,Balance Scale,Multivariate,Classification,Categorical,625,4,1994
12,Balloons,Multivariate,Classification,Categorical,16,4,N/A
13,Breast Cancer,Multivariate,Classification,Categorical,286,9,1988
14,Breast Cancer Wisconsin (Original),Multivariate,Classification,Integer,699,10,1992
15,Breast Cancer Wisconsin (Prognostic),Multivariate,"Classification, Regression",Real,198,34,1995
16,Breast Cancer Wisconsin (Diagnostic),Multivariate,Classification,Real,569,32,1995
17,Pittsburgh Bridges,Multivariate,Classification,"Categorical, Integer",108,13,1990
18,Car Evaluation,Multivariate,Classification,Categorical,1728,6,1997
19,Census Income,Multivariate,Classification,"Categorical, Integer",48842,14,1996
20,Chess (King-Rook vs. King-Knight),"Multivariate, Data-Generator",Classification,"Categorical, Integer",N/A,22,1988
21,Chess (King-Rook vs. King-Pawn),Multivariate,Classification,Categorical,3196,36,1989
22,Chess (King-Rook vs. King),Multivariate,Classification,"Categorical, Integer",28056,6,1994
23,Chess (Domain Theories),Domain-Theory,N/A,N/A,N/A,N/A,N/A
24,Bach Chorales,"Univariate, Time-Series",N/A,"Categorical, Integer",100,6,N/A
25,Connect-4,"Multivariate, Spatial",Classification,Categorical,67557,42,1995
26,Credit Approval,Multivariate,Classification,"Categorical, Integer, Real",690,15,N/A
27,Japanese Credit Screening,"Multivariate, Domain-Theory",Classification,"Categorical, Real, Integer",125,N/A,1992
28,Computer Hardware,Multivariate,Regression,Integer,209,9,1987
29,Contraceptive Method Choice,Multivariate,Classification,"Categorical, Integer",1473,9,1997
30,Covertype,Multivariate,Classification,"Categorical, Integer",581012,54,1998
31,Cylinder Bands,Multivariate,Classification,"Categorical, Integer, Real",512,39,1995
32,Dermatology,Multivariate,Classification,"Categorical, Integer",366,33,1998
33,Diabetes,"Multivariate, Time-Series",N/A,"Categorical, Integer",N/A,20,N/A
34,DGP2 - The Second Data Generation Program,Data-Generator,N/A,Real,N/A,N/A,N/A
35,Document Understanding,N/A,N/A,N/A,N/A,N/A,1994
36,EBL Domain Theories,N/A,N/A,N/A,N/A,N/A,N/A
37,Echocardiogram,Multivariate,Classification,"Categorical, Integer, Real",132,12,1989
38,Ecoli,Multivariate,Classification,Real,336,8,1996
39,Flags,Multivariate,Classification,"Categorical, Integer",194,30,1990
40,Function Finding,N/A,Function-Learning,Real,352,N/A,1990
41,Glass Identification,Multivariate,Classification,Real,214,10,1987
42,Haberman's Survival,Multivariate,Classification,Integer,306,3,1999
43,Hayes-Roth,Multivariate,Classification,Categorical,160,5,1989
44,Heart Disease,Multivariate,Classification,"Categorical, Integer, Real",303,75,1988
45,Hepatitis,Multivariate,Classification,"Categorical, Integer, Real",155,19,1988
46,Horse Colic,Multivariate,Classification,"Categorical, Integer, Real",368,27,1989
47,ICU,"Multivariate, Time-Series",N/A,Real,N/A,N/A,N/A
48,Image Segmentation,Multivariate,Classification,Real,2310,19,1990
49,Internet Advertisements,Multivariate,Classification,"Categorical, Integer, Real",3279,1558,1998
50,Ionosphere,Multivariate,Classification,"Integer, Real",351,34,1989
51,Iris,Multivariate,Classification,Real,150,4,1988
52,ISOLET,Multivariate,Classification,Real,7797,617,1994
53,Kinship,Relational,Relational-Learning,Categorical,104,12,1990
54,Labor Relations,Multivariate,N/A,"Categorical, Integer, Real",57,16,1988
55,LED Display Domain,"Multivariate, Data-Generator",Classification,Categorical,N/A,7,1988
56,Lenses,Multivariate,Classification,Categorical,24,4,1990
57,Letter Recognition,Multivariate,Classification,Integer,20000,16,1991
58,Liver Disorders,Multivariate,N/A,"Categorical, Integer, Real",345,7,1990
59,Logic Theorist,Domain-Theory,N/A,N/A,N/A,N/A,N/A
60,Lung Cancer,Multivariate,Classification,Integer,32,56,1992
61,Lymphography,Multivariate,Classification,Categorical,148,18,1988
62,Mechanical Analysis,Multivariate,Classification,"Categorical, Integer, Real",209,8,1990
63,Meta-data,Multivariate,Classification,"Categorical, Integer, Real",528,22,1996
64,Mobile Robots,Domain-Theory,N/A,"Categorical, Integer, Real",N/A,N/A,1995
65,Molecular Biology (Promoter Gene Sequences),"Sequential, Domain-Theory",Classification,Categorical,106,58,1990
66,Molecular Biology (Protein Secondary Structure),Sequential,Classification,Categorical,128,N/A,N/A
67,Molecular Biology (Splice-junction Gene Sequen...,"Sequential, Domain-Theory",Classification,Categorical,3190,61,1992
68,MONK's Problems,Multivariate,Classification,Categorical,432,7,1992
69,Moral Reasoner,Domain-Theory,N/A,N/A,202,N/A,1994
70,Multiple Features,Multivariate,Classification,"Integer, Real",2000,649,N/A
71,Mushroom,Multivariate,Classification,Categorical,8124,22,1987
72,Musk (Version 1),Multivariate,Classification,Integer,476,168,1994
73,Musk (Version 2),Multivariate,Classification,Integer,6598,168,1994
74,Nursery,Multivariate,Classification,Categorical,12960,8,1997
75,Othello Domain Theory,Domain-Theory,N/A,N/A,N/A,N/A,1991
76,Page Blocks Classification,Multivariate,Classification,"Integer, Real",5473,10,1995
77,Optical Recognition of Handwritten Digits,Multivariate,Classification,Integer,5620,64,1998
78,Pen-Based Recognition of Handwritten Digits,Multivariate,Classification,Integer,10992,16,1998
79,Post-Operative Patient,Multivariate,Classification,"Categorical, Integer",90,8,1993
80,Primary Tumor,Multivariate,Classification,Categorical,339,17,1988
81,Prodigy,Domain-Theory,N/A,N/A,N/A,N/A,N/A
82,Qualitative Structure Activity Relationships,Domain-Theory,N/A,N/A,N/A,N/A,N/A
83,Quadruped Mammals,"Multivariate, Data-Generator",Classification,Real,N/A,72,1992
84,Servo,Multivariate,Regression,"Categorical, Integer",167,4,1993
85,Shuttle Landing Control,Multivariate,Classification,Categorical,15,6,1988
86,Solar Flare,Multivariate,Regression,Categorical,1389,10,1989
87,Soybean (Large),Multivariate,Classification,Categorical,307,35,1988
88,Soybean (Small),Multivariate,Classification,Categorical,47,35,1987
89,Challenger USA Space Shuttle O-Ring,Multivariate,Regression,Integer,23,4,1993
90,Low Resolution Spectrometer,Multivariate,Classification,"Integer, Real",531,102,1988
91,Spambase,Multivariate,Classification,"Integer, Real",4601,57,1999
92,SPECT Heart,Multivariate,Classification,Categorical,267,22,2001
93,SPECTF Heart,Multivariate,Classification,Integer,267,44,2001
94,Sponge,Multivariate,Clustering,"Categorical, Integer",76,45,N/A
95,Statlog Project,N/A,N/A,N/A,N/A,N/A,1992
96,Student Loan Relational,Domain-Theory,N/A,N/A,1000,N/A,1993
97,Teaching Assistant Evaluation,Multivariate,Classification,"Categorical, Integer",151,5,1997
98,Tic-Tac-Toe Endgame,Multivariate,Classification,Categorical,958,9,1991
99,Thyroid Disease,"Multivariate, Domain-Theory",Classification,"Categorical, Real",7200,21,1987

'Multivariate'